# Generated by Django 3.0.4 on 2020-03-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('company_id', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=50)),
                ('use_yn', models.CharField(blank=True, max_length=1, null=True)),
                ('rmk', models.CharField(blank=True, max_length=200, null=True)),
                ('upd_d', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_list',
                'managed': False,
            },
        ),
    ]
