# Generated by Django 3.0.4 on 2020-03-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_stockprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockChangeHis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('rmk', models.CharField(blank=True, max_length=200, null=True)),
                ('upd_d', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_change_his',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=30)),
                ('pod', models.CharField(max_length=1)),
                ('baedang', models.CharField(blank=True, max_length=1, null=True)),
                ('dom_yn', models.CharField(blank=True, max_length=1, null=True)),
                ('cre_d', models.DateTimeField(blank=True, null=True)),
                ('corr_oil', models.FloatField(blank=True, null=True)),
                ('corr_exchange', models.FloatField(blank=True, null=True)),
                ('corr_interest', models.FloatField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockTxn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_seq', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('bos', models.CharField(blank=True, max_length=1, null=True)),
                ('txn_date', models.DateField(blank=True, null=True)),
                ('txn_time', models.DateTimeField(blank=True, null=True)),
                ('company_id', models.CharField(max_length=10)),
                ('txn_yn', models.CharField(blank=True, max_length=1, null=True)),
                ('reset_yn', models.CharField(blank=True, max_length=1, null=True)),
                ('close_yn', models.CharField(blank=True, max_length=1, null=True)),
                ('txn_qty', models.IntegerField(blank=True, null=True)),
                ('txn_price', models.IntegerField(blank=True, null=True)),
                ('txn_fee', models.IntegerField(blank=True, null=True)),
                ('cash_inout', models.IntegerField(blank=True, null=True)),
                ('cash_balance', models.IntegerField(blank=True, null=True)),
                ('asis_price', models.IntegerField(blank=True, null=True)),
                ('target_period', models.IntegerField(blank=True, null=True)),
                ('target_price', models.IntegerField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('bos_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('bos_reason_detail', models.CharField(blank=True, max_length=250, null=True)),
                ('result_review', models.CharField(blank=True, max_length=250, null=True)),
                ('upd_d', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_txn',
                'managed': False,
            },
        ),
    ]
